import type { OrchestrationEmitter } from '../streaming/orchestration-emitter.service';
import type { StreamChunk } from '../streaming/protocol';
import type {
  DevFlowStateType,
  GeneratedArtifact,
  ProjectContract,
  RequirementsDocument,
} from './devflow.state';
import type { DevFlowNodeImpls } from './devflow.graph';
import { NODE } from './topology';

/**
 * Simulation node implementations (Phase 3c).
 *
 * Deterministic, key-free, and event-rich: each node sleeps a realistic amount,
 * streams scripted "thinking" chunks + progress, then returns canned state that
 * matches the real graph's shapes. Wired through the SAME builder/topology as
 * the live graph, so the simulation exercises the full visualizer pipeline
 * (lifecycle, telemetry, agent stream, progress) without any LLM or GitHub
 * access. No external side effects — the gate/mark_delivered infrastructure
 * nodes still write project status (shared with the live graph).
 */

/** Per-step delay, read lazily so it can be tuned (or zeroed in tests) at runtime. */
function stepMs(): number {
  const parsed = Number.parseInt(process.env.SIMULATION_STEP_MS ?? '', 10);
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : 250;
}

function sleep(ms: number): Promise<void> {
  if (ms <= 0) return Promise.resolve();
  return new Promise((resolve) => setTimeout(resolve, ms));
}

interface SimStep {
  type: StreamChunk['type'];
  text: string;
  pct?: number;
}

/**
 * Plays a scripted "thinking" sequence for a node: each step emits an
 * agent.stream chunk (+ optional progress) and waits one tick. Returns the
 * canned result once the script finishes.
 */
async function play(
  emitter: OrchestrationEmitter | null | undefined,
  state: DevFlowStateType,
  nodeId: string,
  steps: SimStep[],
): Promise<void> {
  const { projectId, runId } = state;
  for (const step of steps) {
    const chunk: StreamChunk = {
      nodeId,
      runId: runId ?? '',
      type: step.type,
      chunk: step.text,
    };
    emitter?.agentStream(projectId, runId ?? '', nodeId, [chunk]);
    if (typeof step.pct === 'number') {
      emitter?.nodeProgress(projectId, runId ?? '', nodeId, step.pct, step.text);
    }
    await sleep(stepMs());
  }
}

const SIM_TECH_STACK = {
  frontend: 'Next.js',
  backend: 'NestJS',
  database: 'PostgreSQL',
  styling: 'Tailwind CSS',
};

function artifact(
  agentType: GeneratedArtifact['agentType'],
  filePath: string,
  language: string,
): GeneratedArtifact {
  return {
    agentType,
    filePath,
    language,
    content: `// [simulation] ${filePath}\n// Deterministic placeholder generated by simulation mode.\n`,
  };
}

export function buildSimulationNodeImpls(
  emitter: OrchestrationEmitter | null,
): DevFlowNodeImpls {
  return {
    [NODE.PARSE_REQUIREMENTS]: async (state) => {
      await play(emitter, state, NODE.PARSE_REQUIREMENTS, [
        { type: 'decision', text: 'Reading project brief and prior memories…', pct: 20 },
        { type: 'token', text: 'Identifying core features and constraints…', pct: 60 },
        { type: 'decision', text: 'Requirements drafted (complex).', pct: 100 },
      ]);
      const requirements: RequirementsDocument = {
        projectType: 'SaaS Dashboard',
        features: ['Auth', 'Billing', 'Dashboard', 'Notifications', 'Admin', 'Reporting'],
        techStack: SIM_TECH_STACK,
        complexity: 'complex',
        estimatedFiles: 18,
      };
      return { requirements, complexity: 'complex' };
    },

    [NODE.NEGOTIATE_CONTRACT]: async (state) => {
      await play(emitter, state, NODE.NEGOTIATE_CONTRACT, [
        { type: 'decision', text: 'Drafting architecture contract…', pct: 30 },
        { type: 'tool-call', text: 'Locking file manifest and acceptance criteria.', pct: 80 },
        { type: 'decision', text: 'Contract ready for Gate 1.', pct: 100 },
      ]);
      const requirements: RequirementsDocument = state.requirements ?? {
        projectType: 'SaaS Dashboard',
        features: ['Auth', 'Dashboard'],
        techStack: SIM_TECH_STACK,
        complexity: 'complex',
        estimatedFiles: 18,
      };
      const contract: ProjectContract = {
        projectId: state.projectId,
        projectName: state.companyName || 'Simulated Project',
        description: 'Simulated architecture contract for UI testing.',
        requirements,
        fileManifest: [
          'app/page.tsx',
          'src/main.ts',
          'prisma/schema.prisma',
          'ARCHITECTURE.md',
        ],
        acceptanceCriteria: [
          'App boots and renders the dashboard',
          'API exposes documented endpoints',
          'Schema migrates cleanly',
        ],
        lockedAt: new Date().toISOString(),
      };
      return { contract };
    },

    [NODE.FRONTEND_AGENT]: async (state) => {
      await play(emitter, state, NODE.FRONTEND_AGENT, [
        { type: 'decision', text: 'Scaffolding Next.js app shell…', pct: 25 },
        { type: 'token', text: 'Building dashboard layout and routes…', pct: 65 },
        { type: 'decision', text: 'Frontend artifacts generated.', pct: 100 },
      ]);
      return {
        artifacts: [
          artifact('frontend', 'app/page.tsx', 'tsx'),
          artifact('frontend', 'app/layout.tsx', 'tsx'),
        ],
      };
    },

    [NODE.BACKEND_AGENT]: async (state) => {
      await play(emitter, state, NODE.BACKEND_AGENT, [
        { type: 'decision', text: 'Wiring NestJS modules and auth…', pct: 25 },
        { type: 'token', text: 'Implementing controllers and services…', pct: 65 },
        { type: 'decision', text: 'Backend artifacts generated.', pct: 100 },
      ]);
      return {
        artifacts: [
          artifact('backend', 'src/main.ts', 'ts'),
          artifact('backend', 'src/app.module.ts', 'ts'),
        ],
      };
    },

    [NODE.DATABASE_AGENT]: async (state) => {
      await play(emitter, state, NODE.DATABASE_AGENT, [
        { type: 'decision', text: 'Designing Prisma schema…', pct: 30 },
        { type: 'tool-call', text: 'Generating migration and seed…', pct: 75 },
        { type: 'decision', text: 'Database artifacts generated.', pct: 100 },
      ]);
      return {
        artifacts: [artifact('database', 'prisma/schema.prisma', 'prisma')],
      };
    },

    [NODE.ARCHITECTURE_AGENT]: async (state) => {
      await play(emitter, state, NODE.ARCHITECTURE_AGENT, [
        { type: 'decision', text: 'Summarizing system architecture…', pct: 40 },
        { type: 'token', text: 'Writing ARCHITECTURE.md and API docs…', pct: 85 },
        { type: 'decision', text: 'Architecture docs generated.', pct: 100 },
      ]);
      return {
        artifacts: [artifact('architecture', 'ARCHITECTURE.md', 'markdown')],
      };
    },

    [NODE.SELF_CRITIQUE]: async (state) => {
      await play(emitter, state, NODE.SELF_CRITIQUE, [
        { type: 'decision', text: 'Reviewing artifacts against contract…', pct: 50 },
        { type: 'decision', text: 'Self-critique passed.', pct: 100 },
      ]);
      return {};
    },

    [NODE.VALIDATE_OUTPUTS]: async (state) => {
      await play(emitter, state, NODE.VALIDATE_OUTPUTS, [
        { type: 'decision', text: 'Checking artifacts against the contract…', pct: 50 },
        { type: 'decision', text: 'All checks passed.', pct: 100 },
      ]);
      return { error: null };
    },

    [NODE.COMMIT_TO_GITHUB]: async (state) => {
      await play(emitter, state, NODE.COMMIT_TO_GITHUB, [
        { type: 'tool-call', text: 'Creating repository (simulated)…', pct: 40 },
        { type: 'tool-call', text: 'Committing artifacts (simulated)…', pct: 90 },
        { type: 'decision', text: 'Delivery simulated — no external calls made.', pct: 100 },
      ]);
      return { repoUrl: 'https://github.com/devflow-simulation/demo' };
    },
  };
}
