import type { TemplateContext } from '../types';

export function frontendLayout(ctx: TemplateContext): string {
  return [
    "import type { Metadata } from 'next';",
    "import '../styles/globals.css';",
    '',
    'export const metadata: Metadata = {',
    `  title: '${ctx.contract.projectName}',`,
    "  description: 'Generated by DevFlow',",
    '};',
    '',
    'export default function RootLayout({ children }: { children: React.ReactNode }) {',
    '  return (',
    '    <html lang="en">',
    '      <body>{children}</body>',
    '    </html>',
    '  );',
    '}',
    '',
  ].join('\n');
}
